# Cleaning Data

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("raw_data.csv")

## Handling Missing Values

In [8]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [11]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [12]:
demo = df.copy()

In [13]:
demo

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [16]:
demo.dropna(axis = 1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [17]:
demo

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [18]:
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [20]:
df["age"].fillna(0)

0     29.0
1     29.0
2      0.0
3      0.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9      0.0
10    31.0
Name: age, dtype: float64

In [22]:
demo

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## now changing data in demo

In [23]:
age_means = demo["age"].mean()
demo["age"] = demo["age"].fillna(age_means)

In [24]:
demo

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [25]:
print(age_means)

32.75

In [26]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [27]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
demo.drop_duplicates(inplace = True)

In [31]:
demo

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

## Data type (dtypes)

In [32]:
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [47]:
demo["age"] = demo["age"].astype("int64")

In [49]:
demo.dtypes

id           int64
name           str
age          int64
country        str
gender         str
income     float64
dtype: object

## Date and Time

In [59]:
aqi_data = pd.read_csv("globalAirQuality.csv")

In [61]:
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [64]:
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

In [65]:
aqi_data["timestamp"].dtype

dtype('<M8[us]')

In [66]:
demo

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith   32  Canada   Female  62000.0
3    3          Alex   32     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      NaN
5    5        Li Wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    Ahmed Khan   38     NaN     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz   32  Mexico     Male  45000.0
10  10   Emily Davis   31     USA      NaN  58000.0

In [67]:
demo["name"] = demo["name"].str.lower()

In [68]:
demo

    id          name  age country   gender   income
0    1      john doe   29     USA     Male  55000.0
2    2    jane smith   32  Canada   Female  62000.0
3    3          alex   32     USA  Unknown  47000.0
4    4  maria garcia   34   Spain   Female      NaN
5    5        li wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    ahmed khan   38     NaN     Male  68000.0
8    8    rachel lee   29     USA   Female  62000.0
9    9   carlos ruiz   32  Mexico     Male  45000.0
10  10   emily davis   31     USA      NaN  58000.0

In [69]:
demo["name"] = demo["name"].str.capitalize()

In [70]:
demo

    id          name  age country   gender   income
0    1      John doe   29     USA     Male  55000.0
2    2    Jane smith   32  Canada   Female  62000.0
3    3          Alex   32     USA  Unknown  47000.0
4    4  Maria garcia   34   Spain   Female      NaN
5    5        Li wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    Ahmed khan   38     NaN     Male  68000.0
8    8    Rachel lee   29     USA   Female  62000.0
9    9   Carlos ruiz   32  Mexico     Male  45000.0
10  10   Emily davis   31     USA      NaN  58000.0

In [72]:
demo["name"].str.split(" ")

0         [John, doe]
2       [Jane, smith]
3              [Alex]
4     [Maria, garcia]
5           [Li, wei]
6                 NaN
7       [Ahmed, khan]
8       [Rachel, lee]
9      [Carlos, ruiz]
10     [Emily, davis]
Name: name, dtype: object