## DataFrame

In [3]:
import pandas as pd

In [4]:
info = {
    "Name" : ["Adem","Eve","Bob"],
    "Age" : [23,24,25],
    "GPA" : [9.5,8.5,7.2]
}
df = pd.DataFrame(info)
df

   Name  Age  GPA
0  Adem   23  9.5
1   Eve   24  8.5
2   Bob   25  7.2

### creating DataFrame using list of list

In [8]:
df2 = pd.DataFrame([["Adem",23],["Eve",24],["Bob",25]],columns = ["Name","Age"])
df2

   Name  Age
0  Adem   23
1   Eve   24
2   Bob   25