In [1]:
import pandas as pd

## CSV and json data load

In [4]:
csv = pd.read_csv("raw_data.csv")
print(csv, type(csv))

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0 <class 'pandas.DataFrame'>

In [5]:
read_json = pd.read_json("datajs.json")
print(read_json,type(read_json))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

## some different data load
* read_excel = pd.read_excel("filename")
* read_excel = pd.read_sql("filename")

## using different method on csv load

In [6]:
a = csv

In [7]:
a

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [9]:
a.head()  # print 5 row from start

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

In [11]:
a.tail()  # print last 5 row

    id         name   age country  gender   income
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [12]:
a.tail(7)

    id          name   age country  gender   income
4    4  Maria Garcia  34.0   Spain  Female      NaN
5    5        Li Wei  27.0   China    Male  51000.0
6    6           NaN  45.0   India  Female  73000.0
7    7    Ahmed Khan  38.0     NaN    Male  68000.0
8    8    Rachel Lee  29.0     USA  Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10   Emily Davis  31.0     USA     NaN  58000.0

In [25]:
a.head(n=8)

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN
5   5        Li Wei  27.0   China     Male  51000.0
6   6           NaN  45.0   India   Female  73000.0
7   7    Ahmed Khan  38.0     NaN     Male  68000.0

In [24]:
a.sample(n=4) # or a.sample(4)

    id          name   age country  gender   income
1    1      John Doe  29.0     USA    Male  55000.0
9    9   Carlos Ruiz   NaN  Mexico    Male  45000.0
4    4  Maria Garcia  34.0   Spain  Female      NaN
10  10   Emily Davis  31.0     USA     NaN  58000.0

In [26]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     str
 2   age      8 non-null      float64
 3   country  10 non-null     str
 4   gender   10 non-null     str
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 849.0 bytes

In [28]:
a.shape

(11, 6)

In [29]:
a.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [30]:
a.nunique()

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64